### Gets all movies
GET http://127.0.0.1:3000/movies

### Adds a new movie
POST http://127.0.0.1:3000/movies
Content-Type: application/json

{
  "title": "Avitar",
  "year": "2010",
  "plot": "Some people do VR and go to a land where people are blue.",
  "director": "James Cameron",
  "runtime": 195
}
### Update Movie data
PUT http://127.0.0.1:3000/movies/8
Content-Type: application/json

{

  "title": "Titanic",
  "year": "1998",
  "plot":  " There is a boat. And an iceberg. And people drowning.",
  "director": "James Cameron",
  "runtime": 220
  
}

### Remove movie from db
DELETE http://127.0.0.1:3000/movies/7
Content-Type: application/json

####Actors Routes####
### Adds an Actor
POST http://127.0.0.1:3000/actors
Content-Type: application/json

{
  "first_name": "Fred",
  "last_name": "Durts",
  "known_for": "Weird Movie",
  "age": "27",
  "gender": "male"
}
### Updates actors info
PUT http://127.0.0.1:3000/actors/25
Content-Type: application/json

{
  "first_name": "Fred",
  "last_name": "Derf",
  "known_for": "HAppy Movie",
  "age": "50",
  "gender": "female"
}

### Delete Actors
DELETE http://127.0.0.1:3000/actors/10
Content-Type: application/json 